### ISSUE TITLE
자동 배포 환경 구성

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/TDTD_Backend#1]
# 자동 배포 환경 구성
> AWS에 인스턴스를 생성하고, 애플리케이션 자동 빌드 및 배포 환경을 구성한다.

## ✅ Task List

- [x] AWS EC2 인스턴스 생성 및 서버 환경 설정
- [x] AWS RDS 인스턴스 생성 및 DB 세팅
- [x] EC2와 RDS 연동
- [x] 애플리케이션 배포
- [x] Github Action을 이용하여 CI 적용
- [x] AWS Code Deploy를 이용하여 CD 적용

---

### 💡 고려사항

- AWS 프리티어 이용하기
- profile 설정하기 (local, prod)

<br>

> #### Reference
> - [이동욱님 책: 스프링 부트와 AWS로 혼자 구현하는 웹 서비스](https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=218568947)
