### ISSUE TITLE
롤링페이퍼 방 관련 API 보완

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/TDTD_Backend#17]
# 롤링페이퍼 방 관련 API 보완
> 구현된 롤링페이퍼 방 관련 API들의 놓친 로직과 수정할 부분을 보완한다.

## ✅ Task List

- [x] ~~모든 Entity의 PK값 Null 허용 제거~~
- [x] RoomResponse host -> isHost 처리
- [x] 방 만들기에서 host를 방에 참여시키는 로직 추가
- [x] 방 상세보기에서 isBlinded true처리된 것은 목록에서 제외
- [x] 모호한 Exception 수정 및 messege 추가

---

### 💡 고려사항

- Entity ID값을 Nullable-> Non-Nullable 로 변경하려 했으나,  
  ID를 `0`으로 초기화 하는 것 보다 `null`로 초기화 하는 것이 새로운 Entity임을 의미하는 것에 대한 모호성이 없기에  
 변경하는 작업을 취소하도록 한다.

<br>

> #### Reference
> [Kotlin JPA entity ID](https://stackoverflow.com/questions/49747891/kotlin-jpa-entity-id)
