### ISSUE TITLE
테스트용 더미 데이터 등록

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/TDTD_Backend#18]
# 테스트용 더미 데이터 등록
> 테스트를 위한 더미 데이터를 등록한다.

## ✅ Task List

- [x] User 데이터 등록
- [x] Room 데이터 등록
- [x] Comment 데이터 등록
- [x] Participation 데이터 등록
- [x] Report 데이터 등록

---

### 💡 고려사항

- ooo

<br>

> #### Reference
> NULL

**Comment by jongnan** [comment]
DB 테이블 변경으로 인한 테스트용 더미 데이터 변경 (reopen)
