### ISSUE TITLE
Entity Class 생성

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/TDTD_Backend#2]
# Entity Class 생성
> 설계한 Database 테이블을 토대로 Entity Class를 생성한다.

## ✅ Task List

- [x] 5개의 Entity Class 작성
- [x] 각 해당하는 Repository Interface 작성
- [ ] Entity 간의 관계 설정
- [ ] Index 설정

---

### 💡 고려사항

- Join Column은 설정하지 않는다.

<br>

> #### Reference
> NULL
