### ISSUE TITLE
API Response 형태 변경 및 Custom Exception

### ISSUE THREAD

**Issue by jongnan** [mash-up-kr/TDTD_Backend#20]
# API Response 형태 변경 및 Custom Exception
> HTTP Status만으로는 설명하기 어려운 부분을 보완하기 위함으로 Response 형태를 변경한다.
> Exception 발생 시에도 동일한 Response 형태로 응답하기 위해 Custom Exception을 정의한다.

### Format
```
response: {
    "code" : 200,  // 임의로 정한 상태코드
    "msg" : null,  // 상태에 대한 메시지
    "result" : {
	   // 기존 Response
    }
}
```

## ✅ Task List

- [x] Custom Response 정의
- [x] Custom Exception 정의 및 Handling
- [x] 모든 Response의 형태를 동일하게 감싸주는 Response Entity 정의
- [x] 모든 API Response 형태 변경

---

### 💡 고려사항

- Front 팀들과 상의해서 상태코드와 메시지를 정립해야 함

<br>

> #### Reference
> NULL

**Comment by xyzzeong** [comment]
Done
