### ISSUE TITLE
[긴급] RDS 인스턴스 변경

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/TDTD_Backend#33]
# [긴급] RDS 인스턴스 변경
> 사용중인 AWS RDS를 삭제하고, 새 인스턴스로 데이터를 옮긴다.

저번 서버 마이그레이션 작업을 진행하면서 RDS를 옮길 때 스냅샷을 찍고 복원하여 진행하였는데,
이 복원 과정에서 RDS가 프리티어가 아닌 요금이 부과되는 인스턴스로 생성이 됨.

그래서 예상치 못하게 서버 비용이 크게 발생하였고, 이를 해결하기 위해 RDS 인스턴스 변경이 필요해짐.
(과금된 부분에 대해 AWS 측에서 도와주기 위해서는 지금 요금이 발생하고 있는 것들이 중단되어야 한다고 함)

저번처럼 스냅샷 복원으로는 프리티어를 이용할 수 없어서 새 인스턴스를 먼저 만들고 DB를 덤프해서 복원해야 함.

## ✅ Task List

- [x] AWS 측에 문의 남기기
- [x] AWS RDS에 새 인스턴스 생성
- [x] 기존 데이터베이스 Dump
- [x] 새 데이터베이스에 Restore
- [x] 새 db 인스턴스와 EC2 연결
- [x] prod 환경 db 접속 주소 변경 후 재배포
- [ ] AWS 측에 재 문의하여 과금된 건에 대해 해결

---

### 💡 고려사항

- 기존 인스턴스 이름을 old로 변경해두면서 배포 환경이 꼬이게 됨 -> 해결

<br>

> #### Reference
> NULL
